### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nightscape** [RodrigoNascCarvalho/tdd-expression-interpreter#1]
Hi @RodrigoNascCarvalho!

I'd like to do a Scala introduction at the university and was looking for simple and nice Java code that can be transformed to Scala.
The interpreter pattern is something that can show a lot of nice constructs of the Scala language, so I was searching Github for corresponding Java projects.
Your tdd-expression-interpreter would be a good fit because it's well written and small enough to be introduced to the audience in a reasonable time.

Would you mind if I use your project for that case?
Could you add a license that allows me to do this? I'd publish the source code, too, so I'd also be fine with GPL or something alike.

Best
  Martin

**Comment by RodrigoNascCarvalho** [comment]
Hey Martin,

Just added a GPL license for this repo. You can use it with no problems.

I would love to see the code in Scala later too. :)

Enjoy,
Rodrigo

2017-06-29 18:57 GMT-03:00 Martin Mauch <notifications@github.com>:

> Hi @RodrigoNascCarvalho
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rodrigonasccarvalho&d=DwMCaQ&c=kj4KSSBt5oOaHuCCpWXkZw&r=qkl9XAwb7ymYrUw6h2mcTorD2pPIeOBxtERnDOmL2uM&m=s79CxcreN99zM2cvEGPymYPsOjRevH-uoZq3PD0Gquo&s=xxZVOWbbp9TVHKDxF1U5aSqy2njislf8fprAxFnRbaI&e=>
> !
>
> I'd like to do a Scala introduction at the university and was looking for
> simple and nice Java code that can be transformed to Scala.
> The interpreter pattern is something that can show a lot of nice
> constructs of the Scala language, so I was searching Github for
> corresponding Java projects.
> Your tdd-expression-interpreter would be a good fit because it's well
> written and small enough to be introduced to the audience in a reasonable
> time.
>
> Would you mind if I use your project for that case?
> Could you add a license that allows me to do this? I'd publish the source
> code, too, so I'd also be fine with GPL or something alike.
>
> Best
> Martin
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_RodrigoNascCarvalho_tdd-2Dexpression-2Dinterpreter_issues_1&d=DwMCaQ&c=kj4KSSBt5oOaHuCCpWXkZw&r=qkl9XAwb7ymYrUw6h2mcTorD2pPIeOBxtERnDOmL2uM&m=s79CxcreN99zM2cvEGPymYPsOjRevH-uoZq3PD0Gquo&s=dgJupY5AlEMc2LDB-b9wSBx1R-e5otHaOfFmkVYXQ2I&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGS-2DIAXuJ90wkWNQiBYGpFSFdge12Unuks5sJB3AgaJpZM4OJ6uf&d=DwMCaQ&c=kj4KSSBt5oOaHuCCpWXkZw&r=qkl9XAwb7ymYrUw6h2mcTorD2pPIeOBxtERnDOmL2uM&m=s79CxcreN99zM2cvEGPymYPsOjRevH-uoZq3PD0Gquo&s=jH13IelKx2t3NyRUoouaxoFSPxhVC_DNDH8DznjNxU0&e=>
> .
>



-- 
[]'s

Rodrigo Nascimento de Carvalho

**Comment by nightscape** [comment]
The semi-converted Scala code is here: https://github.com/crealytics/tdd-expression-interpreter
I'll be refining it a little more and trying to make the Git history and comments more or less self-explaining.

Thanks a lot Rodrigo!
